### ISSUE TITLE
Logo proposal

### ISSUE THREAD

**Issue by Tobaloidee** [malkouz/MKColorPicker#3]
Good day @malkouz  I am a graphics designer and I thought of contributing to your good project by designing a logo as a gift for free. If you will allow me, i will start my design and post here when done.

Thanks and best regards!
-Tobaloidee

**Comment by malkouz** [comment]
Hello @Tobaloidee, Go ahead my friend, waiting for your best design.

Thank you very much for you warm contribution.
-Moayad Al kouz

**Comment by Tobaloidee** [comment]
Hi @malkouz  here's my design proposal. I hope you like it! still open for modification

![pres-02-02](https://user-images.githubusercontent.com/36028424/41956104-193558b2-7a15-11e8-9335-aa8653150f0b.png)
